### ISSUE TITLE
after cmake, generated makefile doesn't contain install rule

### ISSUE THREAD

**Issue by marcosins** [gasevi/pyreclab#1]
After executing `cmake .`, the generated makefile doesn't contain the `install` rule.

On my system (Xubuntu 16.04) when i try `make install` it throws an error

```
$ make install
make: *** No hay ninguna regla para construir el objetivo 'install'.  Alto.

$ make help
The following are some of the valid targets for this Makefile:
... all (the default if no target is provided)
... clean
... depend
... edit_cache
... rebuild_cache
... target
... pyreclab
... dataio
... datahandlers
... algorithms
... pyinterface
... eval_metrics
```
---
I can succesfully install with `easy_install` and the egg file generated in ./dist

**Comment by gasevi** [comment]
Hi Marco,

   make install command has been restored in CMakeLists file through setuptools utility.

Thanks!

GSV.

**Comment by marcosins** [comment]
Thank you
