### ISSUE TITLE
first tag

### ISSUE THREAD

**Issue by lalanne** [gasevi/pyreclab#15]
I think the first tag should be opened. Once all the things in master work properly I think a tag should be opened, as the first release of pyreclab.

This way we can start to advanced the development of new features in master at a faster pace and if somebody want the stable version can use the tag.

**Comment by lalanne** [comment]
check #16

**Comment by gasevi** [comment]
Probably you're right, but I still have some little goals to reach before that. Coming soon, very soon :)
