### ISSUE TITLE
Declaration of class "smatrix_t"

### ISSUE THREAD

**Issue by KunlinY** [gasevi/pyreclab#18]
Where is the declaration of smatrix_t? I am curious about the methods of that class. I can not find it in the repository or the boost library..

**Comment by gasevi** [comment]
Hi @KunlinY !,

   if you are looking for the definition of smatrix_t owned by RatingMatrix class, you can find it in the same directory. It is the class SparseMatrix defined in file SparseMatrix.cpp.
   On the other hand, the boost library is a standard library often used in C++ to implement a lot of patterns. Take a look of https://www.boost.org/.

Best,

GSV.

**Comment by KunlinY** [comment]
Thanks!!

**Comment by gasevi** [comment]
you are welcome!
