### ISSUE TITLE
Error in IFAls instance

### ISSUE THREAD

**Issue by Hernan4444** [gasevi/pyreclab#20]
Hi, 

I'm posting this issue to notificate an error. Readme.md shows that the generic format for creating one of these instances is
```python
>>> obj = pyreclab.RecAlg( dataset = filename,
                           dlmchar = b'\t',
                           header = False,
                           usercol = 0,
                           itemcol = 1,
                           ratingcol = 2 )
```

But in IFAls , when I try to creat an instances, I have the following error;
```python
TypeError: 'ratingcol' is an invalid keyword argument for this function
```
I think the error are in AlgFactory.cpp that IFAls and IFAlsConjugateGradient were not include in `getInstance` and in IFAls.cpp, the arguments of the instance are: 

```c++
AlgIFAls::AlgIFAls( DataReader& dreader,
                    int userpos,
                    int itempos,
                    int obspos )
```

But in another algorithm are:
```c++

AlgFunkSvd::AlgFunkSvd( DataReader& dreader,
                        int userpos,
                        int itempos,
                        int ratingpos )
```

**Comment by gasevi** [comment]
Hi Hernan,

   thank you for  your report  !.
   The problem is not related with the factory because it is not used anymore. What version of pyreclab are you using ?.

**Comment by gasevi** [comment]
The readme was fixed and update !
