### ISSUE TITLE
Not being able to install using anaconda. Giving No url found error.

### ISSUE THREAD

**Issue by AshuAkshi0708** [gasevi/pyreclab#21]
Could not find a version that satisfies the requirement pyreclab (from versions: )
No matching distribution found for pyreclab

**Comment by gasevi** [comment]
Hi @farzanaaswin0708 , thanks for your report !

could you give me some details about the operating system where you are running Anaconda ?, type, version, etc.

Best,

GSV.

**Comment by gasevi** [comment]
I got no additional information from this report.
