### ISSUE TITLE
Ejecución de ejemplos - pyreclab

### ISSUE THREAD

**Issue by ANDRESHZ** [gasevi/pyreclab#23]
una vez compiladas, construidas e instaladas para **python 3.8** de manera exitosa según lo indicado por la Terminal
obtuve y validado
`pip3 install pyreclab`

> Requirement already satisfied: pyreclab in ./anaconda3/lib/**python3.8**/site-packages/pyreclab-0.1.14-py3.8-linux-x86_64.egg (0.1.14)

permitiendo realizar la importación dentro de los programas de Python
al intentar correr cualquier ejemplo no encuentra los atributos puestos para el funcionamiento en ninguno de ellos: 
```
cd pyreclab/examples/
python3.8 testBprMf.py 
```

> Traceback (most recent call last):  File "testBprMf.py", line 6, in <module>    bprmf = pyreclab.BprMf( factors = 20, AttributeError: module 'pyreclab' has no attribute '_BprMf_'

`python3.8 testFunkSvd.py`
> Traceback (most recent call last):  File "testFunkSvd.py", line 6, in <module>    svd = pyreclab.SVD( factors = 1000,AttributeError: module 'pyreclab' has no attribute '_SVD_'
`python3.8 testIFAlsCg.py `
> Traceback (most recent call last):  File "testIFAlsCg.py", line 6, in <module>    ifalscg = pyreclab.IFAlsConjugateGradient( factors = 50,AttributeError: module 'pyreclab' has no attribute '_IFAlsConjugateGradient_'
`python3.8 testIFAls.py `

> Traceback (most recent call last):   File "testIFAls.py", line 6, in <module>    ifals = pyreclab.IFAls( factors = 50,AttributeError: module 'pyreclab' has no attribute '_IFAls_'

`python3.8 testItemAvg.py `

> Traceback (most recent call last):  File "testItemAvg.py", line 6, in <module>    iavg = pyreclab.ItemAvg( dataset = 'dataset/u1.base',AttributeError: module 'pyreclab' has no attribute '_ItemAvg_'

…
…
…
`python3.8 testUserKnn.py `

> Traceback (most recent call last):  File "testUserKnn.py", line 6, in <module>
>     ubknn = pyreclab.UserKnn( dataset = 'dataset/u1.base', AttributeError: module 'pyreclab' has no attribute '_UserKnn_

'

¿A alguno le ha pasado? Estoy en un ambiente local (Pues mi idea es poder replicar posteriormente sin COLAB)

**Comment by gasevi** [comment]
Hola @ANDRESHZ ,

   actualmente, pyreclab no está soportado para python 3.8. Seguramente hubo un cambio en la interfaz para definir los módulos que incluye el paquete.
   Esto no debería suceder en Colab dado que ellí se utiliza python 3.6.
   Si no tienes opción más que usarlo en Python 3.8, puedo evaluar liberar un wheel en estos días para esa versión.

Saludos!

**Comment by ANDRESHZ** [comment]
Gracias, si es que las librerías que trabajó en desde Anaconda navigator en unos desarrollo y en unos notebooks ya estan basadas sobre el **3.8**, me tocaria cambiar algunos programas en los que trabajo.

Momentáneamente instalaré **Python3.6** en otro ambiente y trabajaré allí así cuando logre migrar solo es pasar codigo de ambiente. 
muchas gracias

**Comment by gasevi** [comment]
Perfecto !

Aprovecho de preguntar, ¿ qué sistema operativo usas ?.

**Comment by ANDRESHZ** [comment]
Ubuntu 20.04 y Windows 10 en ambos tengo instanciados Python (3.8 y 3.6 segun sugeriste) y Anaconda

**Comment by gasevi** [comment]
Hola @ANDRESHZ ,

   hice un cambio que creo corregirá tu problema. ¿ Podrías intentar hacer un git pull y luego repetir el proceso de instalación por favor ?.
   Cuando vayas a correr los ejemplos con Python 3.8, probablemente ahora te fallará el módulo time por no encotrar la función clock():

AttributeError: module 'time' has no attribute 'clock'

   Para resolver eso, simplemente reemplaza la función clock() por perf_counter().

Quedo atento!

@gasevi

**Comment by ANDRESHZ** [comment]
Perfecto si permitió realizar la importación sobre 3.8, eres muy amable 

> -> training model
> [==================================================] 100.0 % - ET 00:00:16 ETA 00:00:00
> training time: 16.18502722300002
> recommendation for user 457: ['475', '255', '150', '250', '763']
> -> recommendation test
> recommendation time: 0.132377517000009
> MAP: 0.5893481881644338
> nDCG: 0.4564460474419385
> user 10 MAP: 0.5845238183225904
> user 10 nDCG: 0.5676818673666728


Sobre ubuntu 20.04, sobre windows no logre encontrar las "librerías" adecuadas para su construcción con Cmake (solo pude ponerles el boost y el Visual 2015) muchísimas gracias

**Comment by gasevi** [comment]
Excelente !.

Sí, por el momento no hay soporte para Windows. Principalmente porque hay que hacer la traducción de algunos llamados a sistema que hacen más complejo el asunto.

Antes de cerrar el issue, una última pregunta: ¿ Por qué no instalaste pyreclab a través de pip3.8 en Ubuntu 20 ?. Ahora que le doy una vuelta, eso debería funcionar sin problema.

**Comment by ANDRESHZ** [comment]
lo intente, al principio pero no funciono decía, algo que no se cumplian los requerimeintos, y pues como ya lo tenia instalado posteriormente pues preferí hacer el pull y construir nuevamente.

`pip3 install pyreclab`

> `Requirement already satisfied: pyreclab in /home/bahz/anaconda3/lib/python3.8/site-packages/pyreclab-0.1.14-py3.8-linux-x86_64.egg (0.1.14)`

**Comment by gasevi** [comment]
Gracias!

**Comment by gasevi** [comment]
Hola @ANDRESHZ ,

   pyreclab ya está disponible para python 3.8 y ubuntu 20.20 para instalar desde pip.

Saludos,

GSV.
