### ISSUE TITLE
Guardar modelo en .pickle

### ISSUE THREAD

**Issue by dlcartagena** [gasevi/pyreclab#25]
Hola, me gustaría saber si existe alguna forma de guardar un modelo en un archivo pickle. Lo intenté y me tira el siguiente error: 
<img width="730" alt="Captura de Pantalla 2020-12-10 a la(s) 16 57 33" src="https://user-images.githubusercontent.com/37153544/101822926-d688d180-3b08-11eb-8817-45b5c9d7af58.png">

**Comment by gasevi** [comment]
Hola @dlcartagena,

   lamentablemente no es posible almacenar los objetos en pickle debido a que el modelo se mantiene en formato binario.
   Si necesitas almacenar alguno en particular, quizás pueda hacer un desarrollo rápido para dar soporte al almacenamiento. ¿ Por ahora solo necesitas UserBasedKnn ?.
   Esto es para el curso de RecSys en la PUC, ¿ cierto ?.

Saludos,

GSV.

**Comment by dlcartagena** [comment]
Ahh entiendo. Es para el curso Minería de datos en la PUC, necesito guardar los modelos UserKNN, ItemKNN y Most Popular, pero los necesito para mañana, así que no creo que sea viable de realizar en tan poco tiempo.

Muchas gracias, saludos!

**Comment by gasevi** [comment]
Lo lamento. Espero poder dar soporte al almacenamiento pronto.
Saludos,
GSV.
