### ISSUE TITLE
pip install failing

### ISSUE THREAD

**Issue by alansaid** [gasevi/pyreclab#26]
pip install failing when attempting to install pyreclab

`~/work/Rec|⇒  pip install pyreclab`
`ERROR: Could not find a version that satisfies the requirement pyreclab`
`ERROR: No matching distribution found for pyreclab`

python 3.7.3 on pyenv on macos.

**Comment by gasevi** [comment]
Hi @alansaid,

   thanks for your report !. Could you tell me which OS and version you are using ?.

Best.

**Comment by alansaid** [comment]
> Hi @alansaid,
> 
> thanks for your report !. Could you tell me which OS and version you are using ?.
> 
> Best.

MacOS Catalina (10.15.7)

**Comment by alansaid** [comment]
Same problem in Big Sur.

**Comment by gasevi** [comment]
Hi @alansaid,

   I've just uploaded a new version for MacOS Catalina to pypi. Please try installing and running it, and let me know how it goes.

Best.

**Comment by alansaid** [comment]
It worked! Can you please do the same for Big Sur?

**Comment by gasevi** [comment]
nice ! :) ... I'm going to try to install Big Sur during the day so that I can compile pyreclab on that version. Do you need the package for python 3.7 too ?

Best.

**Comment by alansaid** [comment]
3.7 would be great, yes.

**Comment by alansaid** [comment]
Seems there's some issue with the library though

`File "/Users/alan/.pyenv/versions/tools3/lib/python3.7/site-packages/pyreclab/__init__.py", line 12, in <module>`
`    from pyreclab.libpyreclab import MostPopular, UserAvg, ItemAvg, SlopeOne, UserKnn, ItemKnn, SVD, IFAls, IFAlsConjugateGradient, BprMf`
`ImportError: dlopen(/Users/alan/.pyenv/versions/tools3/lib/python3.7/site-packages/pyreclab/libpyreclab.so, 2): Library not loaded: /usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/Python`
`  Referenced from: /Users/alan/.pyenv/versions/3.7.3/envs/tools3/lib/python3.7/site-packages/pyreclab/libpyreclab.so
  Reason: image not found`

This happens when `import pyreclab` is issued

**Comment by gasevi** [comment]
Hi @alansaid,

   are you trying to load pyreclab froma virtual env ?. Could you send me more information about the context of the error ?

GSV.

**Comment by gasevi** [comment]
Hi @alansaid,

   do you have more information about this case ?

Best.
GSV.
