### ISSUE TITLE
input command line: cmake . 

### ISSUE THREAD

**Issue by kyowill** [gasevi/pyreclab#3]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PYTHON_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/will/pyreclab
   used as include directory in directory /home/will/pyreclab
   used as include directory in directory /home/will/pyreclab/dataio
   used as include directory in directory /home/will/pyreclab/datahandlers
   used as include directory in directory /home/will/pyreclab/algorithms
   used as include directory in directory /home/will/pyreclab/pyinterface
   used as include directory in directory /home/will/pyreclab/eval_metrics

**Comment by kyowill** [comment]
https://stackoverflow.com/questions/24174394/cmake-is-not-able-to-find-python-libraries
It works

**Comment by Vince-Valence** [comment]
Hello @kyowill, I am having the same problem, how did you solve it? I saw the question in SO, but it has no accepted answer.

**Comment by kyowill** [comment]
add this option
-DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")

**Comment by Vince-Valence** [comment]
Thank you, @kyowill. It worked.
